from database import items_col, orders_col, suppliers_col


SEED_ITEMS = [
    {
        "id": 1,
        "name": "Fabric",
        "unit": "kg",
        "planned_qty": 100,
        "planned_rate": 250,
        "actual_qty": 110,
        "actual_rate": 260,
        "current_stock": 200,
        "minimum_stock": 80,
        "daily_consumption": 40,
        "lead_time_days": 4,
        "safety_stock": 80,
        "supplier_name": "Rajesh Textiles",
        "production_value": 4200,
        "worker_cost": 1800,
        "delay_history": 2,
    },
    {
        "id": 2,
        "name": "Thread",
        "unit": "cones",
        "planned_qty": 200,
        "planned_rate": 45,
        "actual_qty": 190,
        "actual_rate": 48,
        "current_stock": 80,
        "minimum_stock": 40,
        "daily_consumption": 50,
        "lead_time_days": 3,
        "safety_stock": 40,
        "supplier_name": "Kumar Yarns",
        "production_value": 2100,
        "worker_cost": 1800,
        "delay_history": 5,
    },
    {
        "id": 3,
        "name": "Buttons",
        "unit": "pcs",
        "planned_qty": 500,
        "planned_rate": 2,
        "actual_qty": 520,
        "actual_rate": 2.5,
        "current_stock": 300,
        "minimum_stock": 150,
        "daily_consumption": 100,
        "lead_time_days": 2,
        "safety_stock": 150,
        "supplier_name": "Shiva Accessories",
        "production_value": 1500,
        "worker_cost": 1800,
        "delay_history": 1,
    },
    {
        "id": 4,
        "name": "Zipper",
        "unit": "pcs",
        "planned_qty": 150,
        "planned_rate": 18,
        "actual_qty": 140,
        "actual_rate": 17,
        "current_stock": 500,
        "minimum_stock": 60,
        "daily_consumption": 30,
        "lead_time_days": 5,
        "safety_stock": 60,
        "supplier_name": "Metro Zippers",
        "production_value": 3200,
        "worker_cost": 1800,
        "delay_history": 0,
    },
    {
        "id": 5,
        "name": "Lining",
        "unit": "meters",
        "planned_qty": 80,
        "planned_rate": 120,
        "actual_qty": 90,
        "actual_rate": 125,
        "current_stock": 50,
        "minimum_stock": 30,
        "daily_consumption": 20,
        "lead_time_days": 3,
        "safety_stock": 30,
        "supplier_name": "Decent Fabrics",
        "production_value": 3800,
        "worker_cost": 1800,
        "delay_history": 3,
    },
]

SEED_ORDERS = [
    {
        "id": 1,
        "order_code": "ORD-2024-001",
        "start_date": "15 Jan 2024",
        "planned_total": 38000,
        "actual_total": 41200,
        "variance_total": 3200,
        "status": "Over Budget",
    },
    {
        "id": 2,
        "order_code": "ORD-2024-002",
        "start_date": "18 Jan 2024",
        "planned_total": 27500,
        "actual_total": 26800,
        "variance_total": -700,
        "status": "Under Budget",
    },
    {
        "id": 3,
        "order_code": "ORD-2024-003",
        "start_date": "22 Jan 2024",
        "planned_total": 45000,
        "actual_total": 48750,
        "variance_total": 3750,
        "status": "Over Budget",
    },
    {
        "id": 4,
        "order_code": "ORD-2024-004",
        "start_date": "28 Jan 2024",
        "planned_total": 52000,
        "actual_total": 50100,
        "variance_total": -1900,
        "status": "Under Budget",
    },
    {
        "id": 5,
        "order_code": "ORD-2024-005",
        "start_date": "05 Feb 2024",
        "planned_total": 31000,
        "actual_total": 34200,
        "variance_total": 3200,
        "status": "Over Budget",
    },
]

SEED_SUPPLIERS = [
    {
        "id": 1,
        "supplier_name": "Rajesh Textiles",
        "item": "Fabric",
        "contact": "+91 98400 11111",
        "promised_lead_days": 4,
        "actual_lead_days": 5,
        "price_change_percent": 4,
        "reliability_score": 7.2,
        "grade": "B+",
    },
    {
        "id": 2,
        "supplier_name": "Kumar Yarns",
        "item": "Thread",
        "contact": "+91 98400 22222",
        "promised_lead_days": 3,
        "actual_lead_days": 3,
        "price_change_percent": 6.7,
        "reliability_score": 8.9,
        "grade": "A",
    },
    {
        "id": 3,
        "supplier_name": "Shiva Accessories",
        "item": "Buttons",
        "contact": "+91 98400 33333",
        "promised_lead_days": 2,
        "actual_lead_days": 2,
        "price_change_percent": 25,
        "reliability_score": 6.1,
        "grade": "B",
    },
    {
        "id": 4,
        "supplier_name": "Metro Zippers",
        "item": "Zipper",
        "contact": "+91 98400 44444",
        "promised_lead_days": 5,
        "actual_lead_days": 4,
        "price_change_percent": -5.6,
        "reliability_score": 9.4,
        "grade": "A+",
    },
    {
        "id": 5,
        "supplier_name": "Decent Fabrics",
        "item": "Lining",
        "contact": "+91 98400 55555",
        "promised_lead_days": 3,
        "actual_lead_days": 4,
        "price_change_percent": 4.2,
        "reliability_score": 7.8,
        "grade": "B+",
    },
]


async def seed_database():
    """Insert seed data only if collections are empty."""
    if await items_col.count_documents({}) == 0:
        await items_col.insert_many(SEED_ITEMS)
        print("✓ Seeded inventory_items")

    if await orders_col.count_documents({}) == 0:
        await orders_col.insert_many(SEED_ORDERS)
        print("✓ Seeded orders")

    if await suppliers_col.count_documents({}) == 0:
        await suppliers_col.insert_many(SEED_SUPPLIERS)
        print("✓ Seeded suppliers")
